language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tshala/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tshala/docker-react npm run test